name    'leonardothibes-util'
author  'leonardothibes'
version '1.0.0'
license 'MIT'
summary 'My Standard Library for Puppet Modules'
description 'This module provides a "standard library" of resources for developing Puppet Modules'
source 'git://github.com/leonardothibes/puppet-util.git'
project_page 'http://github.com/leonardothibes/puppet-util'
